#include <stdio.h>

#define PAGE_TABLE_PERMISSION_BIT 0x7
#define USER_ACCESSIBLE_PAGES_BIT 0x7
#define KERNEL_ACCESSIBLE_PAGES_BIT 0x3
#define CHILD_PROCESS_READ_ONLY_PAGES_BIT 0x5
#define COW_PAGES_BIT 0x805

#define VIDEO_MEMORY_POINTER_ADDRESS 0xffffffff70000000

#define USER_STACK_ADDRESS_END_LIMIT 0x00000000fffe0000 //vma end
#define USER_STACK_ADDRESS_START 0x00000000fffefff8 //vma start

//#define USER_STACK_ADDRESS_END_LIMIT 0x0000000080000000 //vma end
//#define USER_STACK_ADDRESS_START 0x000000008000fff8 //vma start

#define UINT64_T_STACK_SIZE 512

#define SYSCALL_READ 	0
#define SYSCALL_WRITE	1
#define SYSCALL_FORK 	2

#define PCB_LIST_LENGTH 200

#define PCB_FD_LIST_LENGTH 32
#define PCB_FD_FREE_POINTER 0
#define PCB_FD_NON_FREE_POINTER 1
#define PCB_FD_TYPE_FILE_BACKED 1
#define PCB_FD_TYPE_TERMINAL_BACKED 0

#define FILE_READ_BUFFER_LENGTH 10000
#define NORMAL_READ_BUFFER_LENGTH 300

#define TARFS_CHILDREN_NODE_LIMIT 128

#define TARFS_CHILDREN_FOLDER_TYPE 5
#define TARFS_CHILDREN_FILE_TYPE 0

#define TARFS_FILE_FOLDER_MAX_NAME_LENGTH 128
#define TARFS_MAX_PATH_DEPTH 10
